<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<PackageId>DawnestOfBread.UltralightNet.AppCore</PackageId>
		<Description>AppCore bindings</Description>
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>

		<!-- <PackageLicenseFile>LICENSE.txt</PackageLicenseFile> -->
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="System.ValueTuple" Version="4.5.0" PrivateAssets="All"/>
		<ProjectReference Include="..\UltralightNet\UltralightNet.csproj"/>
		<PackageReference Include="DawnestOfBread.UltralightNet.AppCore.Binaries" Version="$(UltralightVersion)"/>
	</ItemGroup>

</Project>
