<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<PackageId>DawnestOfBread.UltralightNet.AppCore.Binaries</PackageId>
		<Version>$(UltralightVersion)</Version>

		<Platform>x64</Platform>

		<Authors>Ultralight, Inc.</Authors>
		<Copyright>Ultralight, Inc.</Copyright>
		<Description>AppCore binaries</Description>

		<!-- <PackageLicenseFile>LICENSE.txt</PackageLicenseFile> -->
		<PackageLicenseExpression>LGPL-2.1-only</PackageLicenseExpression>
		<PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
	</PropertyGroup>
	<ItemGroup>
		<!-- <None Include="LICENSE.txt" Pack="true" PackagePath="LICENSE.txt"/> -->
		<!-- <None Include="EULA.txt" Pack="true" PackagePath="EULA.txt"/> -->
		<!-- <None Include="NOTICES.txt" Pack="true" PackagePath="NOTICES.txt"/> -->
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="DawnestOfBread.UltralightNet.Binaries" Version="$(UltralightVersion)" />

		<_NativeAssetName Include="runtimes/win-x64/native/AppCore.dll" PackagePath="runtimes/win-x64/native" />
		<_NativeAssetName Include="runtimes/osx-x64/native/libAppCore.dylib" PackagePath="runtimes/osx-x64/native" />
		<_NativeAssetName Include="runtimes/linux-x64/native/libAppCore.so" PackagePath="runtimes/linux-x64/native" />

		<_ExistingAssets Include="@(_NativeAssetName)" />
		<Content Include="@(_ExistingAssets->'%(Identity)')" CopyToOutputDirectory="PreserveNewest" PackagePath="%(PackagePath)" Pack="true" />
	</ItemGroup>
</Project>
